{{- if and .Values.rbac.create .Values.rbac.nodeExec.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vke-cluster-agent.fullname" . }}-node-exec
  labels:
    {{- include "vke-cluster-agent.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.nodeExec.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vke-cluster-agent.fullname" . }}-node-exec
  labels:
    {{- include "vke-cluster-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vke-cluster-agent.fullname" . }}-node-exec
subjects:
- kind: ServiceAccount
  name: {{ include "vke-cluster-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }} 