apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "vke-cluster-agent.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vke-cluster-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vke-cluster-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vke-cluster-agent.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      priorityClassName: system-cluster-critical
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vke-cluster-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          env:
            {{- range $key, $value := .Values.environments }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
          - mountPath: /var/run/dbus/system_bus_socket
            name: dbus-socket
          - mountPath: /run/systemd/system
            name: host-systemd
          - mountPath: /etc/rancher/rke2/rke2.yaml
            name: rke2-kubeconfig
            readOnly: true
          args:
            - "-v={{ .Values.agent.verbosityLevel }}"
      volumes:
      - name: dbus-socket
        hostPath:
          path: /var/run/dbus/system_bus_socket
          type: Socket
      - name: host-systemd
        hostPath:
          path: /run/systemd/system
          type: Directory
      - name: rke2-kubeconfig
        hostPath:
          path: /etc/rancher/rke2/rke2.yaml
          type: FileOrCreate
      nodeSelector:
        kubernetes.io/os: linux
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 