# Working directory
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/agent"
bin = "tmp/main"

# Customize binary.
full_bin = "./tmp/main -v=4"

# This log file places in your tmp_dir.
log = "air_errors.log"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html"]
# Exclude specific regular expressions.
exclude_regex = ["_test.go"]
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms

[log]
# Show log time
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

# Added for the new configuration
include_dir = []
exclude_file = []
stop_on_error = true