name: Release Chart

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "info@vmind.com.tr"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        run: |
          docker build --no-cache --platform=linux/amd64 -t vmindtech/vke-cluster-agent:${GITHUB_REF##*/} .
          docker push vmindtech/vke-cluster-agent:${GITHUB_REF##*/}

      - name: Helm Deps
        run: |
          helm dep update charts/vke-cluster-agent
      
      - name: Helm Add Repo
        run: |
          helm dependency list charts/vke-cluster-agent | tail -n +2 | awk '{print $1, $3}' | while read name url; do
            helm repo add "$name" "$url"
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
