name: Release Chart

on:
  push:
    branches:
      - "main"
      - "release-*"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "info@vmind.com.tr"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        run: |
          docker build --no-cache --platform=linux/amd64 -t vmindtech/vke-cluster-agent:${GITHUB_REF##*/} .
          docker push vmindtech/vke-cluster-agent:${GITHUB_REF##*/}

      - name: Helm Deps
        run: |
          helm dep update chart/vke-cluster-agent
      
      - name: Helm Add Repo
        run: |
          helm dependency list chart/vke-cluster-agent | tail -n +2 | awk '{print $1, $3}' | while read name url; do
            helm repo add "$name" "$url"
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          chart_path: chart/vke-cluster-agent
          github_token: ${{ secrets.ACTION_SECRET }}
          chart_releaser_token: ${{ secrets.ACTION_SECRET }}
          release_name: ${{ github.event.repository.name }}
          release_version: ${{ github.sha }}
          release_message: ${{ github.event.head_commit.message }}
          release_commit: ${{ github.sha }}
          release_files: chart/vke-cluster-agent/*.tgz
          release_files_glob: true
          release_prerelease: false
          release_draft: false
          release_replace: true
          release_debug: true
          release_skip_upload: false
          release_skip_upload_glob: false
          release_skip_upload_files: ""
